name: foundation-test

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: "true"
  TF_STATE_BUCKET: kuflink-test-states
  TF_LOCK_TABLE: kuflink-tf-locks-test
  ROLE_ARN: arn:aws:iam::137167813802:role/kuflink-test-github-oidc-terraform

jobs:
  foundation:
    name: foundation
    runs-on: [self-hosted, tf-runner]
    permissions:
      id-token: write
      contents: read
    env:
      LAYER: foundation
      TF_WORKDIR: environments/test-git/foundation
      TF_STATE_KEY: test-git/foundation/terraform.tfstate

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test Terraform Path
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          $terraformPath = "C:\Users\M.Ayanda\OneDrive - Kuflink Group\Desktop\Malik Kuflink\terraform\terraform.exe"
          Write-Host "Testing terraform at: $terraformPath"
          if (Test-Path $terraformPath) {
            Write-Host "Terraform found!"
            & $terraformPath version
          } else {
            Write-Host "Terraform NOT found at expected path"
            Write-Host "Searching for terraform.exe..."
            Get-ChildItem -Path C:\ -Recurse -Name "terraform.exe" -ErrorAction SilentlyContinue | Select-Object -First 5
          }

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          $terraformPath = "C:\Users\M.Ayanda\OneDrive - Kuflink Group\Desktop\Malik Kuflink\terraform\terraform.exe"
          & $terraformPath init -backend-config="bucket=$env:TF_STATE_BUCKET" -backend-config="key=$env:TF_STATE_KEY" -backend-config="region=$env:AWS_REGION" -backend-config="dynamodb_table=$env:TF_LOCK_TABLE" -backend-config="encrypt=true"

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKDIR }}
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          $terraformPath = "C:\Users\M.Ayanda\OneDrive - Kuflink Group\Desktop\Malik Kuflink\terraform\terraform.exe"
          & $terraformPath plan -input=false -out=tfplan.bin
          & $terraformPath show -no-color tfplan.bin > tfplan.txt
          Write-Host "Plan completed successfully"